### PR TITLE
I Updated points.ts to make it do Username and User Id

### PR DESCRIPTION
**Pull request by Joshua-M07**
Hope this works XD

### CODE REVIEW

**Comment by Joshua-M07** [comment]
This should work by looking at your current code as of this was from my other bot sorry for saying "Hope this works"

**Comment by austinmccalley** [comment]
Please actually test it.

**Comment by Joshua-M07** [comment]
I have it should work and im not sure how to test it tho

**Comment by Joshua-M07** [comment]
`message.guild.members.cache.find(m => m.user.username === args.join(' ')) : message.guild.members.cache.find(m => m.user.id === args.join(' '))`
will work as of it works on my bot

**Comment by Joshua-M07** [comment]
my bad

**Pull request closed without merging**
